name: 'Jira Check Issue Status'
description: 'check the Jira issue status'
author: 'Michael Hakim'
inputs:
  organization-name: 
    description: 'The name of the organization on Jira'
    required: true
    default: 'hatchedlabs'
  jira-token:  
    description: 'Jira Token'
    required: true
runs:
  using: "composite"
  steps:
      - name: Get Issue Status
        shell: bash
        run: |
          Response=$(curl --location --request GET "https://${{ inputs.organization-name }}.atlassian.net/rest/api/3/issue/${{steps.issue_name.outputs.name}}?fields=status" \
          --header 'Accept: application/json' \
          --header "Authorization: ${{ secrets.JIRA_TOKEN }}" )
           echo "##[set-output name=status;]$(echo $Response | jq '.fields.status.name')"
           echo $Response | jq '.fields.status.name'
        id: issue_status
      - name: Try to fail
        shell: bash
        run: |
          if [[ ! ${{steps.issue_status.outputs.status}} =~ "In Progress" ]]; then
            echo "Your issue on JIRA still not in progress."
            exit 1
          fi 
branding:
  icon: 'check-circle'  
  color: 'orange'